### ISSUE TITLE
Bin fertig

### ISSUE THREAD

**Issue by CoolTuxNet** [gardena-smart-reverse-engineering/deGardenServer#1]
https://github.com/fhem/GardenaSmart/tree/devel

Sorry ich musste etwas umdisponieren. Kannst Du bitte die Version einmal testen mit Deinem lokalen Server.

Grüße

**Comment by SciLor** [comment]
Ich habe selbst kein fhem im Einsatz.
Laut Implementierung deines Codes sieht alles sauber aus.

https://github.com/fhem/GardenaSmart/issues/3

**Comment by CoolTuxNet** [comment]
Sehr schön. Na dann schauen wir mal wenn sich die ersten User melden.
